development:
  adapter: async

test:
  adapter: async

production:
  adapter: <%= ENV.fetch("CABLE_ADAPTER") { "redis" } %>
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: rails_websocket_bench_production
